### ISSUE TITLE
Feature request: Show deletion-type variants as a range, not a single line.

### ISSUE THREAD

**Issue by ifokkema** [DCRT-LUMC/exonviz#3]
I tried replacing the default variant input to `NM_003002.4:c.[274G>T;300_400del]` and expected a bar drawn to show the deletion of bases 300 to 400, but the program only drew a thin bar at position 300. Although adding a range will cause variants to overlap more frequently, it would help showing the range of an actual deletion.

**Comment by Redmar-van-den-Berg** [comment]
We discussed adding this functionality, but in the end decided on only showing the position of the variants for simplicity. The reasoning behind this is that we show the transcript as-is, and highlight the position of variants, without changing the transcript itself. This way, the behavior is consistent between insertions, deletions and other types of variants.

**Comment by ifokkema** [comment]
> (...) decided on only showing the position of the variants for simplicity. (...) This way, the behavior is consistent between insertions, deletions and other types of variants.

It's actually not. My point is that you're _not_ showing the position of the variant at all. You're only showing the first base deleted, not the rest. Obviously, it's hard to handle overlapping variants, but by highlighting only the first base, you're not showing the position of the variant. Now, it's kind of an arbitrary choice of whether to show the first, middle, or last base deleted.

**Comment by Redmar-van-den-Berg** [comment]
This is correct, we only show the position of the first base of the variant, as described in HGVS. I agree this is kind of arbitrary, but so are all variant positions when using HGVS.
